### ISSUE TITLE
Notifications popup needs a scrollbar

### ISSUE THREAD

**Issue by leansoli** [tipvote/tipvote_webapp#34]
Hey, OtroMasDeSistemas here :)

I took some days off and I have these many notifications: https://imgur.com/a/wexQCc2

If I clicked 'mark all as read' I would then have to go to my notifications history and do the count manually to know which ones I saw and clicked on the notification popup and which ones were flagged as read because I couldn't scroll to see them.

**Comment by Anekdotin** [comment]
Fixed
