### ISSUE TITLE
Docker webapp for easy get up and running

### ISSUE THREAD

**Issue by Anekdotin** [tipvote/tipvote_webapp#5]
Including postgres with schemas.  Should be a turn key thing for newcommers.

**Comment by leansoli** [comment]
Hey, OtroMasDeSistemas here :)

I took some days off and after returning I have 17 notifications. It would be handy to have a scrollbar if the notifications are too many;
[Screen capture](https://imgur.com/a/wexQCc2)

If I clicked 'mark all as read' I would then have to go to the historical notifications and do the count manually to know which ones I clicked through the popup and which ones I marked as read before actually reading them.

**Comment by Anekdotin** [comment]
Thank you to superleaf1995
